spring.application.name=vuhoangchinh

# Cấu hình kết nối MySQL (Tự động tạo database nếu chưa tồn tại)
spring.datasource.url=jdbc:mysql://localhost:3306/vuhoangchinh_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Cấu hình JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thay đổi port chạy ứng dụng (mặc định là 8080 nếu không cấu hình)
server.port=8080

# Cấu hình Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs